// AUTO-GENERATED by scripts/embed-python.mjs. Do not edit by hand.
//
// Bundled Python extractor module (embedded as a bunfs asset).
//
// The DIRECT static `import` below makes `bun build --compile` embed this
// zip's bytes into the compiled CLI as a virtual /$bunfs/root/<…> asset.
// At runtime `extractors.ts` writes it to ~/.devlens/extractors/v1/python/
// and prepends it to PYTHONPATH, so `python3 -m devlens_extractors_python`
// (spawned by devlensio) imports straight out of the zip — no venv, no pip.
import zip from "./devlens_python.zip";
export default zip;
