// AUTO-GENERATED by scripts/embed-active.mjs for build target linux-x64
// (devlens platform dir: linux-amd64). Do not edit by hand — re-run the script.
//
// Only ONE platform's go+rust extractor binaries (+ the portable java jar) are
// imported here on purpose: `bun build --compile` embeds exactly these, so a
// compiled binary for this target carries only what it can run. Embedding all
// five platforms would add ~37MB of dead bytes that never execute.
import go from "./go/linux-amd64.js";
import rust from "./rust/linux-amd64.js";
import jar from "./java/jar.js";
import py from "./python/module.js";

/** The ONE platform embedded in THIS build (matches devlensio's platformDir()
 *  for the host, which a per-target compiled binary always runs on). */
export const embeddedPlatform = "linux-amd64" as const;
export { go, rust, jar, py };
