// AUTO-GENERATED by scripts/embed-active.mjs (SOURCE mode) — do not edit.
//
// Source/dev runs only: exports PATH STRINGS instead of static binary
// imports (importing an ELF/jar crashes `bun src/cli/index.ts` with
// "error: Unexpected ELF"). These strings do NOT embed in a compiled
// binary — build-binaries.mjs regenerates the import variant
// (`embed-active.mjs <target>`) before every `bun build --compile` and
// restores this source variant afterwards.
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const ENGINE_EXTRACTORS = path.join(ROOT, "node_modules", "devlensio", "extractors");

/** Host devlens platform dir (matches devlensio's platformDir()). */
export const embeddedPlatform =
  process.platform === "darwin"
    ? (process.arch === "arm64" ? "darwin-arm64" : "darwin-amd64")
    : process.platform === "win32"
      ? "windows-amd64"
      : process.arch === "arm64"
        ? "linux-arm64"
        : "linux-amd64";

const exe = embeddedPlatform === "windows-amd64" ? ".exe" : "";

export const go   = path.join(ENGINE_EXTRACTORS, "go", "bin", embeddedPlatform, `devlens_go_extractor${exe}`);
export const rust = path.join(ENGINE_EXTRACTORS, "rust", "bin", embeddedPlatform, `devlens_rust_extractor${exe}`);
export const jar  = path.join(ENGINE_EXTRACTORS, "java", "devlens_java_extractor.jar");
export const py   = path.join(ROOT, "src", "cli", "embedded", "python", "devlens_python.zip");
