// DevLens CLI — embedded extractor artifacts (per build target).
//
// When built with `bun build --compile`, a DIRECT static `import` of an
// extractor binary (or the python zip) embeds that file's bytes into the
// compiled CLI as a virtual /$bunfs/root/<…> blob (see src/cli/embedded/*.ts).
// At startup (src/cli/preload.ts → ensureExtractorsReady) we read those blobs
// out with fs.readFileSync and write them to a real cache dir under ~/.devlens,
// then point DEVLENS_EXTRACTORS_DIR at it (and PYTHONPATH at the python zip),
// so devlensio's subprocess extractors find real executables to spawn.
//
// Per-target embedding: `active.ts` (generated by scripts/embed-active.mjs)
// imports only ONE platform's go+rust binaries — the platform matching the
// build target — plus the portable java jar and the portable python module
// zip (both platform-independent, so included in every target). A compiled
// binary built for one target only ever runs on that platform, so embedding
// the other four platforms' go/rust would be ~37MB of dead bytes.
// Switching targets = re-run the embed-active script for the new target.
import { go, rust, jar, py, embeddedPlatform } from "./embedded/active.js";

/** The devlens platform dir embedded in THIS build. Matches devlensio's
 *  `platformDir()`: a per-target compiled binary always runs on the platform
 *  it was built for, so this is also the host platform at runtime. */
export function enginePlatformDir(): string {
  return embeddedPlatform;
}

export interface EmbeddedArtifact {
  /** Relative path under the extractors root (what devlensio looks up). */
  rel: string;
  /** Abs path in source mode, or bunfs virtual path in a compiled binary. */
  src: string;
}

/** The artifacts embedded for THIS build target: the host platform's go+rust
 *  binaries, the portable (one-copy) java jar, and the portable python module
 *  zip. Exactly one platform's go/rust — the one this binary can actually run. */
export function embeddedArtifacts(): EmbeddedArtifact[] {
  const platform = enginePlatformDir();
  const exe = platform === "windows-amd64" ? ".exe" : "";
  return [
    { rel: `go/bin/${platform}/devlens_go_extractor${exe}`, src: go },
    { rel: `rust/bin/${platform}/devlens_rust_extractor${exe}`, src: rust },
    { rel: "java/devlens_java_extractor.jar", src: jar },
    { rel: "python/devlens_python.zip", src: py },
  ];
}
