// Generates src/cli/embedded/python/module.ts which embeds the Python extractor
// module as a single bunfs asset, so `python3 -m devlens_extractors_python`
// works out-of-the-box for any user with python3 on PATH — no venv, no pip.
//
// Why a zip and not the raw .py files: the Python extractor
// (`devlens_extractors_python/`, pure stdlib — pyproject.toml has dependencies=[])
// is ~23 files across 3 dirs. Importing each .py as a separate bunfs asset would
// need 23 wrappers. Instead we zip the package once at build time; at runtime we
// keep it AS a zip and put it on PYTHONPATH — Python imports pure-Python modules
// straight out of a zip on sys.path (PEP 273), no extraction step required.
//
// Verified: `echo {"repoPath":...} | PYTHONPATH=devlens_python.zip python3 -m
// devlens_extractors_python` runs identically to an installed venv (3874 nodes
// on the FastAPI repo, no third-party deps needed).
//
// Usage:  node scripts/embed-python.mjs
//         (called automatically by scripts/build-binaries.mjs before each target)
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync, spawnSync } from "node:child_process";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pySrcDir = path.join(root, "node_modules", "devlensio", "extractors", "python");
const pkgDir = path.join(pySrcDir, "devlens_extractors_python");

if (!fs.existsSync(path.join(pkgDir, "__main__.py"))) {
  console.error(`devlens: python extractor module not found at ${pkgDir}`);
  console.error("  run \`bun install\` first (devlensio postinstall may have been skipped).");
  process.exit(1);
}

const zipDir = path.join(root, "src", "cli", "embedded", "python");
const zipPath = path.join(zipDir, "devlens_python.zip");
fs.mkdirSync(zipDir, { recursive: true });
if (fs.existsSync(zipPath)) fs.rmSync(zipPath);

// Build the zip with python3's stdlib zipfile (cross-platform: no `zip` CLI
// needed, works on Windows/macOS/Linux). We write a real temp .py file instead
// of `python3 -c "..."` so the package path — which contains spaces on this
// repo — never collides with shell/python string quoting.
const script = `
import os, sys, zipfile
pkg, out, src = ${JSON.stringify(pkgDir)}, ${JSON.stringify(zipPath)}, ${JSON.stringify(pySrcDir)}
z = zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED)
n = 0
for dp, _dirs, files in os.walk(pkg):
    for f in files:
        full = os.path.join(dp, f)
        rel = os.path.relpath(full, src)
        if "__pycache__" in dp.split(os.sep):
            continue
        z.write(full, rel)
        n += 1
z.close()
print(f"zipped {n} files, {os.path.getsize(out)} bytes -> {out}")
`;
const tmpScript = path.join(os.tmpdir(), `devlens-embed-python-${process.pid}.py`);
fs.writeFileSync(tmpScript, script, "utf8");

// Resolve a working Python interpreter. On Windows `python3` is often the
// Microsoft Store stub (which fails when run), while `python` points at a real
// interpreter — or vice-versa. Probe candidates with `--version` and use the
// first that actually executes.
const pyCandidates = ["python3", "python"];
let pyCmd = null;
for (const c of pyCandidates) {
  try {
    const probe = spawnSync(c, ["--version"], { stdio: "ignore", timeout: 10000 });
    if (probe.status === 0) { pyCmd = c; break; }
  } catch { /* try next */ }
}
if (!pyCmd) {
  console.error("devlens: no working Python interpreter found (tried: " + pyCandidates.join(", ") + ").");
  console.error("  Install Python 3.11+ or make sure `python`/`python3` is on PATH.");
  try { fs.rmSync(tmpScript); } catch { /* best-effort */ }
  process.exit(1);
}

try {
  execSync(`${pyCmd} ${JSON.stringify(tmpScript)}`, { stdio: "inherit" });
} finally {
  try { fs.rmSync(tmpScript); } catch { /* best-effort */ }
}

// Write the wrapper: a DIRECT import of the .zip file so `bun build --compile`
// embeds its bytes as a /$bunfs asset. A plain `export default "<path>"` string
// does NOT embed (that was the original false positive). The absolute path is
// a build-time reference only.
const wrapperPath = path.join(zipDir, "module.ts");
fs.writeFileSync(
  wrapperPath,
  `// AUTO-GENERATED by scripts/embed-python.mjs. Do not edit by hand.\n//\n` +
  `// Bundled Python extractor module (embedded as a bunfs asset).\n//\n` +
  `// The DIRECT static \`import\` below makes \`bun build --compile\` embed this\n` +
  `// zip's bytes into the compiled CLI as a virtual /$bunfs/root/<…> asset.\n` +
  `// At runtime \`extractors.ts\` writes it to ~/.devlens/extractors/v1/python/\n` +
  `// and prepends it to PYTHONPATH, so \`python3 -m devlens_extractors_python\`\n` +
  `// (spawned by devlensio) imports straight out of the zip — no venv, no pip.\n` +
  `import zip from "./devlens_python.zip";\nexport default zip;\n`,
  "utf8",
);
console.log(`✔ wrote ${path.relative(root, wrapperPath)} (zip: ${path.relative(root, zipPath)})`);
