// Generates src/cli/embedded/active.ts — the module that maps the four
// extractor artifacts (go, rust, java jar, python zip) for the CLI.
//
// TWO modes:
//
//   SOURCE mode (default, no args):
//     node scripts/embed-active.mjs
//     Writes a source-safe variant that exports plain PATH STRINGS resolved
//     at runtime (node_modules/devlensio/extractors/... for go/rust/jar, the
//     repo's devlens_python.zip for python). A plain string does NOT embed in
//     a compiled binary — which is fine, because this variant is ONLY for
//     running from a source checkout (`bun src/cli/index.ts …`, bun test).
//     Static binary imports crash source runs outright ("error: Unexpected
//     ELF"), so this variant must never import the binaries.
//
//   BUILD mode (explicit target):
//     node scripts/embed-active.mjs linux-x64
//     node scripts/embed-active.mjs linux-amd64   (devlens platform dir also accepted)
//     Writes the static-import variant that `bun build --compile` embeds as
//     /$bunfs blobs. Build scripts (build-binaries.mjs) regenerate this per
//     target BEFORE compiling and restore SOURCE mode afterwards, so the
//     committed file is always the source-safe one.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "src", "cli", "embedded", "active.ts");

// bun build --target spelling  ->  devlens platform dir (enginePlatformDir()).
const TO_DEVLENS = {
  "darwin-x64": "darwin-amd64",
  "darwin-arm64": "darwin-arm64",
  "linux-x64": "linux-amd64",
  "linux-arm64": "linux-arm64",
  "windows-x64": "windows-amd64",
};

// ── SOURCE mode (default) ─────────────────────────────────────────────────────
if (!process.argv[2] || process.argv[2] === "--source") {
  const code = `// AUTO-GENERATED by scripts/embed-active.mjs (SOURCE mode) — do not edit.
//
// Source/dev runs only: exports PATH STRINGS instead of static binary
// imports (importing an ELF/jar crashes \`bun src/cli/index.ts\` with
// "error: Unexpected ELF"). These strings do NOT embed in a compiled
// binary — build-binaries.mjs regenerates the import variant
// (\`embed-active.mjs <target>\`) before every \`bun build --compile\` and
// restores this source variant afterwards.
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const ENGINE_EXTRACTORS = path.join(ROOT, "node_modules", "devlensio", "extractors");

/** Host devlens platform dir (matches devlensio's platformDir()). */
export const embeddedPlatform =
  process.platform === "darwin"
    ? (process.arch === "arm64" ? "darwin-arm64" : "darwin-amd64")
    : process.platform === "win32"
      ? "windows-amd64"
      : process.arch === "arm64"
        ? "linux-arm64"
        : "linux-amd64";

const exe = embeddedPlatform === "windows-amd64" ? ".exe" : "";

export const go   = path.join(ENGINE_EXTRACTORS, "go", "bin", embeddedPlatform, \`devlens_go_extractor\${exe}\`);
export const rust = path.join(ENGINE_EXTRACTORS, "rust", "bin", embeddedPlatform, \`devlens_rust_extractor\${exe}\`);
export const jar  = path.join(ENGINE_EXTRACTORS, "java", "devlens_java_extractor.jar");
export const py   = path.join(ROOT, "src", "cli", "embedded", "python", "devlens_python.zip");
`;
  fs.writeFileSync(out, code, "utf8");
  console.log(`✔ wrote ${path.relative(root, out)} (SOURCE mode — path strings, no binary imports)`);
  process.exit(0);
}

// ── BUILD mode (explicit target) ─────────────────────────────────────────────
const arg = process.argv[2];
const isBunTarget = arg in TO_DEVLENS;
const platform = isBunTarget ? TO_DEVLENS[arg] : arg; // accept either spelling
const devlensPlatforms = Object.values(TO_DEVLENS);
if (!isBunTarget && !devlensPlatforms.includes(arg)) {
  console.error(
    `devlens: unknown target "${arg}". Expected a bun target ` +
      `(${Object.keys(TO_DEVLENS).join(", ")}) or a devlens platform dir ` +
      `(${devlensPlatforms.join(", ")}), or no argument for SOURCE mode.`,
  );
  process.exit(1);
}

const goFile = path.join(root, "src", "cli", "embedded", "go", `${platform}.ts`);
const rustFile = path.join(root, "src", "cli", "embedded", "rust", `${platform}.ts`);
if (!fs.existsSync(goFile) || !fs.existsSync(rustFile)) {
  console.error(
    `devlens: no embedded wrapper for platform "${platform}" ` +
      `(expected ${path.relative(root, goFile)} and ${path.relative(root, rustFile)}).`,
  );
  process.exit(1);
}

const code = `// AUTO-GENERATED by scripts/embed-active.mjs for build target ${arg}
// (devlens platform dir: ${platform}). Do not edit by hand — re-run the script.
//
// Only ONE platform's go+rust extractor binaries (+ the portable java jar) are
// imported here on purpose: \`bun build --compile\` embeds exactly these, so a
// compiled binary for this target carries only what it can run. Embedding all
// five platforms would add ~37MB of dead bytes that never execute.
import go from "./go/${platform}.js";
import rust from "./rust/${platform}.js";
import jar from "./java/jar.js";
import py from "./python/module.js";

/** The ONE platform embedded in THIS build (matches devlensio's platformDir()
 *  for the host, which a per-target compiled binary always runs on). */
export const embeddedPlatform = "${platform}" as const;
export { go, rust, jar, py };
`;

fs.writeFileSync(out, code, "utf8");
console.log(`✔ wrote ${path.relative(root, out)} for target ${arg} (platform ${platform})`);
