// Generates src/cli/embedded/active.ts for a SINGLE build target so that
// `bun build --compile` embeds only that platform's go+rust extractor binaries
// (+ the portable java jar). A compiled binary built for one target only ever
// runs on that platform, so embedding the other four platforms' binaries would
// be ~37MB of dead bytes that never execute.
//
// Usage:  node scripts/embed-active.mjs linux-x64
//         node scripts/embed-active.mjs linux-amd64   (devlens platform dir also accepted)
//
// Run this BEFORE `bun build ... --target=bun-<os>-<arch>`. The default file
// committed for the dev host is the dev host's own platform; the build
// regenerates it per target, so building the full matrix just runs this once
// per target before each `bun build` (see the build:binaries script).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "src", "cli", "embedded", "active.ts");

// bun build --target spelling  ->  devlens platform dir (enginePlatformDir()).
const TO_DEVLENS = {
  "darwin-x64": "darwin-amd64",
  "darwin-arm64": "darwin-arm64",
  "linux-x64": "linux-amd64",
  "linux-arm64": "linux-arm64",
  "windows-x64": "windows-amd64",
};

const arg = process.argv[2];
const isBunTarget = arg in TO_DEVLENS;
const platform = isBunTarget ? TO_DEVLENS[arg] : arg; // accept either spelling
const devlensPlatforms = Object.values(TO_DEVLENS);
if (!isBunTarget && !devlensPlatforms.includes(arg)) {
  console.error(
    `devlens: unknown target "${arg}". Expected a bun target ` +
      `(${Object.keys(TO_DEVLENS).join(", ")}) or a devlens platform dir ` +
      `(${devlensPlatforms.join(", ")}).`,
  );
  process.exit(1);
}

const goFile = path.join(root, "src", "cli", "embedded", "go", `${platform}.ts`);
const rustFile = path.join(root, "src", "cli", "embedded", "rust", `${platform}.ts`);
if (!fs.existsSync(goFile) || !fs.existsSync(rustFile)) {
  console.error(
    `devlens: no embedded wrapper for platform "${platform}" ` +
      `(expected ${path.relative(root, goFile)} and ${path.relative(root, rustFile)}).`,
  );
  process.exit(1);
}

const code = `// AUTO-GENERATED by scripts/embed-active.mjs for build target ${arg}
// (devlens platform dir: ${platform}). Do not edit by hand — re-run the script.
//
// Only ONE platform's go+rust extractor binaries (+ the portable java jar) are
// imported here on purpose: \`bun build --compile\` embeds exactly these, so a
// compiled binary for this target carries only what it can run. Embedding all
// five platforms would add ~37MB of dead bytes that never execute.
import go from "./go/${platform}.js";
import rust from "./rust/${platform}.js";
import jar from "./java/jar.js";
import py from "./python/module.js";

/** The ONE platform embedded in THIS build (matches devlensio's platformDir()
 *  for the host, which a per-target compiled binary always runs on). */
export const embeddedPlatform = "${platform}" as const;
export { go, rust, jar, py };
`;

fs.writeFileSync(out, code, "utf8");
console.log(`✔ wrote ${path.relative(root, out)} for target ${arg} (platform ${platform})`);
